[workspace]
members = ["wheel"]

[package]
name = "chia"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.129"
clvmr = "=0.1.20"
hex = "=0.4.3"
num-traits = "=0.2.14"
pyo3 = "=0.15.1"

[lib]
name = "chia"
crate-type = ["rlib"]

[profile.release]
lto = true
