[package]
name = "chia_rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.129"
clvm = { git = "https://github.com/Chia-Network/clvm_rs", rev = "8ea5357ff54a2a07452feaf858e80e1c8015a30a" }
hex = "=0.4.3"
num-traits = "=0.2.14"

[target.'cfg(target_os = "macos")'.dependencies]

[lib]
name = "chia_rs"
crate-type = ["cdylib"]

[profile.release]
lto = true

[target.'cfg(not(target_family="wasm"))'.dependencies]
pyo3 = { version = "0.15.1", features = ["abi3-py37"] }
