[package]
name = "chia_rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.129"

[target.'cfg(not(target_os = "macos"))'.dependencies]
clvm_rs = { git = "https://github.com/richardkiss/clvm_rs", branch = "chia_rs" }

[target.'cfg(target_os = "macos")'.dependencies]
clvm_rs = { git = "https://github.com/richardkiss/clvm_rs", branch = "chia_rs", default-features = false }

[lib]
name = "chia_rs"
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true

[target.'cfg(not(target_family="wasm"))'.dependencies]
pyo3 = "0.14.5"
