[workspace]
members = [
    "crates/chia-bls",
    "crates/chia-bls/fuzz",
    "crates/chia-client",
    "crates/chia-consensus",
    "crates/chia-protocol",
    "crates/chia-protocol/fuzz",
    "crates/chia_py_streamable_macro",
    "crates/chia_streamable_macro",
    "crates/chia-ssl",
    "crates/chia-tools",
    "crates/chia-traits",
    "crates/chia-wallet",
    "crates/chia-wallet/fuzz",
    "crates/clvm-derive",
    "crates/clvm-traits",
    "crates/clvm-utils",
    "crates/clvm-utils/fuzz",
    "fuzz",
    "wasm",
    "wheel", "crates/chia-consensus",
]

[package]
name = "chia"
version = "0.5.2"
edition = "2021"
license = "Apache-2.0"
description = "Utility functions and types used by the Chia blockchain full node"
authors = ["Richard Kiss <him@richardkiss.com>", "Arvid Norberg <arvid@chia.net>"]
homepage = "https://github.com/Chia-Network/chia_rs"
repository = "https://github.com/Chia-Network/chia_rs"

[features]
py-bindings = ["dep:pyo3"]

[dependencies]
clvmr = "0.6.0"
hex = "0.4.3"
pyo3 = { version = ">=0.19.0", optional = true }
clvm-utils = { version = "0.5.1", path = "crates/clvm-utils" }
chia-traits = { version = "0.5.2", path = "crates/chia-traits" }
clvm-traits = { version = "0.5.2", path = "crates/clvm-traits" }
clvm-derive = { version = "0.5.2", path = "crates/clvm-derive" }
chia-protocol = { version = "0.5.1", path = "crates/chia-protocol" }
chia-wallet = { version = "0.5.1", path = "crates/chia-wallet" }
hex-literal = "0.4.1"
thiserror = "1.0.44"

[dev-dependencies]
num-traits = "0.2.15"
rstest = "0.16.0"
text-diff = "0.4.0"
criterion = "0.5.1"

[lib]
name = "chia"
crate-type = ["rlib"]
bench = false

[profile.release]
lto = "thin"

[[bench]]
name = "run-generator"
harness = false

[[bench]]
name = "tree-hash"
harness = false

# This is also necessary in `wheel/Cargo.toml` to make sure the `wheel` crate builds as well.
# Pin the `blst` dependency to the correct revision, since the fix has not been properly released yet.
[patch.crates-io]
blst = { git = "https://github.com/supranational/blst.git", rev = "0d46eefa45fc1e57aceb42bba0e84eab3a7a9725" }
