[package]
name = "chia_rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.129"
clvm_rs = { path = "/Users/kiss/projects/chia/clvm_rs/4chia_rs", default-features = false }

[lib]
name = "chia_rs"
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true

[target.'cfg(not(target_family="wasm"))'.dependencies]
pyo3 = "0.14.5"
