# the "wheel" crate is excluded from the workspace because pyo3 has problems with
# "cargo test" and "cargo bench"
[workspace]
members = ["wasm", "chia_streamable_macro", "chia-bls", "clvm-utils"]
exclude = ["wheel"]

[package]
name = "chia"
version = "0.1.14"
edition = "2021"
license = "Apache-2.0"
description = "Utility functions and types used by the Chia blockchain full node"
authors = ["Richard Kiss <him@richardkiss.com>", "Arvid Norberg <arvid@chia.net>"]
homepage = "https://github.com/Chia-Network/chia_rs/"
repository = "https://github.com/Chia-Network/chia_rs/"

[features]
py-bindings = ["dep:pyo3"]

[dependencies]
clvmr = "=0.1.24"
hex = "=0.4.3"
pyo3 = { version = "=0.15.1", features = ["extension-module"], optional = true }
chia_streamable_macro = { version = "=0.2.3", path = "chia_streamable_macro" }
clvm-utils = { version = "=0.1.14", path = "clvm-utils" }

[dev-dependencies]
num-traits = "=0.2.15"

[lib]
name = "chia"
crate-type = ["rlib"]

[profile.release]
lto = true
