[workspace]
members = [
    "crates/chia-bls",
    "crates/chia-bls/fuzz",
    "crates/chia-client",
    "crates/chia-consensus",
    "crates/chia-protocol",
    "crates/chia-protocol/fuzz",
    "crates/chia_py_streamable_macro",
    "crates/chia_streamable_macro",
    "crates/chia-ssl",
    "crates/chia-tools",
    "crates/chia-traits",
    "crates/chia-wallet",
    "crates/chia-wallet/fuzz",
    "crates/clvm-derive",
    "crates/clvm-traits",
    "crates/clvm-utils",
    "crates/clvm-utils/fuzz",
    "fuzz",
    "wasm",
    "wheel",
]

[package]
name = "chia"
version = "0.5.2"
edition = "2021"
license = "Apache-2.0"
description = "A meta-crate that exports all of the Chia crates in the workspace."
authors = [
    "Richard Kiss <him@richardkiss.com>",
    "Arvid Norberg <arvid@chia.net>",
    "Brandon Haggstrom <b.haggstrom@chia.net>"
]
homepage = "https://github.com/Chia-Network/chia_rs"
repository = "https://github.com/Chia-Network/chia_rs"

[dependencies]
chia-bls = { path = "./crates/chia-bls" }
chia-client = { path = "./crates/chia-client" }
chia-consensus = { path = "./crates/chia-consensus" }
chia-protocol = { path = "./crates/chia-protocol" }
chia-ssl = { path = "./crates/chia-ssl" }
chia-traits = { path = "./crates/chia-traits" }
chia-wallet = { path = "./crates/chia-wallet" }
clvm-traits = { path = "./crates/clvm-traits" }
clvm-utils = { path = "./crates/clvm-utils" }
clvmr = "0.6.0"

[dev-dependencies]
criterion = "0.5.1"
hex = "0.4.3"

[profile.release]
lto = "thin"

[[bench]]
name = "run-generator"
harness = false

[[bench]]
name = "tree-hash"
harness = false

# This is also necessary in `wheel/Cargo.toml` to make sure the `wheel` crate builds as well.
# Pin the `blst` dependency to the correct revision, since the fix has not been properly released yet.
[patch.crates-io]
blst = { git = "https://github.com/supranational/blst.git", rev = "0d46eefa45fc1e57aceb42bba0e84eab3a7a9725" }
