[package]
name = "chia-tools"
version = "0.1.16"
edition = "2021"
license = "Apache-2.0"
description = "Utility functions and types used by the Chia blockchain full node"
authors = ["Arvid Norberg <arvid@chia.net>"]
homepage = "https://github.com/Chia-Network/chia_rs/chia-tools"
repository = "https://github.com/Chia-Network/chia_rs/chia-tools"

[dependencies]
chia-protocol = { version = ">=0.2.0", path = "../chia-protocol" }
clvmr = { version = ">=0.2.5", features = ["counters"] }
chia = { path = "..", version = ">=0.2.0" }
sqlite = "=0.30.3"
clap = { version = "=4.0.29", features = ["derive"] }
zstd = "=0.12.1"
threadpool = "=1.8.1"

[[bin]]
name = "analyze-chain"
test = false
bench = false

[[bin]]
name = "test-block-generators"
test = false
bench = false
