[package]
name = "chia-traits"
version = "0.9.0"
edition = "2021"
license = "Apache-2.0"
description = "Chia traits for Streamable types (chia's serialization format)"
authors = ["Arvid Norberg <arvid@chia.net>"]

[features]
py-bindings = ["dep:pyo3"]

[dependencies]
pyo3 = { workspace = true, features = ["multiple-pymethods"], optional = true }
chia_streamable_macro = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
