[package]
name = "chia_rs"
version = "0.1.0"
authors = ["Richard Kiss <him@richardkiss.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Code useful for implementing chia consensus."
homepage = "https://github.com/Chia-Network/clvm_rs/"
repository = "https://github.com/Chia-Network/clvm_rs/"
readme = "README.md"

[lib]
name = "chia_rs"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
chia = { path = ".." }
pyo3 = { version = "=0.15.1", features = ["abi3-py37", "extension-module"] }
