name: Rust crate

on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build_crate:
    name: Build crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Fmt
        run: cargo fmt -- --files-with-diff --check

      - name: Clippy
        run: cargo clippy

      - name: Tests
        run: cargo test && cargo test --release

      - name: Build
        run: cargo build --release

      - name: Upload crate artifacts
        uses: actions/upload-artifact@v4
        with:
          name: crate
          path: ./target/package/*-*.crate

      - name: Publish (crates.io)
        if: startsWith(github.event.ref, 'refs/tags')
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.cargo_registry_token }}
        run: |
          cargo install cargo-workspaces --locked
          cargo ws publish --publish-as-is
